from typing import (Generic, Iterable, Iterator, Sized, Union, List, Dict, Mapping,
                    Optional, overload, AnyStr, Any, Tuple, Sequence, TypeVar, IO)
from lxml.etree import QName, XPath, XMLParser, XSLT, XSLTAccessControl


AnySmartStr = Union['ElementUnicodeResult', 'PyElementUnicodeResult', 'ElementStringResult']
XPathObject = Union[bool, float, AnySmartStr, AnyStr, List[Union['Element', AnySmartStr, AnyStr, Tuple[Optional[AnyStr], Optional[AnyStr]]]]]
ListAnyStr = List[AnyStr]
DictAnyStr = Dict[AnyStr, AnyStr]
Dict_Tuple2AnyStr_Any = Dict[Tuple[AnyStr], Any]
NSMap = Dict[Optional[AnyStr], AnyStr]
xpath = Union['XPath', AnyStr]
Namespace = Mapping[Optional[AnyStr], Any]
T = TypeVar('T')


class ElementUnicodeResult(str):
    is_attribute: bool
    is_tail: bool
    is_text: bool
    attrname: Optional[AnyStr]
    def getparent(self) -> Optional['Element']: ...


class PyElementUnicodeResult(str):
    is_attribute: bool
    is_tail: bool
    is_text: bool
    attrname: Optional[AnyStr]
    def getparent(self) -> Optional['Element']: ...


class ElementStringResult(bytes):
    is_attribute: bool
    is_tail: bool
    is_text: bool
    attrname: Optional[AnyStr]
    def getparent(self) -> Optional['Element']: ...


class Element(Generic[AnyStr], Iterable['Element'], Sized):
    def __delitem__(self, key: Union[int, slice]) -> None: ...
    def __getitem__(self, item: int) -> 'Element[AnyStr]': ...
    def __len__(self) -> int: ...
    def addprevious(self, element: 'Element[AnyStr]') -> None: ...
    def addnext(self, element: 'Element[AnyStr]') -> None: ...
    def append(self, element: 'Element[AnyStr]') -> None: ...
    def cssselect(self, expression: str) -> List['Element[AnyStr]']: ...
    def find(self, path: AnyStr, namespace: Optional[Namespace] = ...) -> Optional['Element[AnyStr]']: ...
    def findall(self,
                name: str,
                namespace: Optional[Namespace] = ...) -> List['Element[AnyStr]']: ...
    def clear(self) -> None: ...
    @overload
    def get(self, key: Union[AnyStr, QName]) -> Optional[AnyStr]: ...
    @overload
    def get(self, key: Union[AnyStr, QName], default: T) -> Union[AnyStr, T]: ...
    def getnext(self) -> Optional['Element[AnyStr]']: ...
    def getparent(self) -> Optional['Element[AnyStr]']: ...
    def getprevious(self) -> Optional['Element[AnyStr]']: ...
    def getroottree(self) -> 'ElementTree[AnyStr]': ...
    def insert(self, index: int, element: 'Element[AnyStr]') -> None: ...
    def iter(self,
             tag: Optional[AnyStr] = ...,
             *tags: AnyStr) -> Iterable['Element[AnyStr]']: ...
    def makeelement(self,
                    _tag: Union[AnyStr, QName],
                    attrib: Optional[DictAnyStr] = ...,
                    nsmap: Optional[NSMap] = ...,
                    **_extra: Any
                    ) -> 'Element[AnyStr]': ...
    def remove(self, element: 'Element[AnyStr]') -> None: ...
    def xpath(self,
              _path: AnyStr,
              namespaces: Optional[DictAnyStr] = ...,
              extensions: Any = ...,
              smart_strings: bool = ...,
              **_variables: XPathObject) -> XPathObject: ...
    @property
    def attrib(self) -> 'Attrib[AnyStr]': ...
    text: Optional[AnyStr] = ...
    tag:  Union[AnyStr, QName] = ...
    tail: Optional[AnyStr] = ...
    @property
    def nsmap(self) -> NSMap: ...
    def __iter__(self) -> 'ElementChildIterator[AnyStr]': ...
    def items(self) -> Sequence[Tuple[AnyStr, AnyStr]]: ...
    def iterfind(self, path: str, namespace: Optional[Namespace] = None)  -> Iterator['Element[AnyStr]']: ...

class ElementChildIterator(Generic[AnyStr], Iterator['Element[AnyStr]']):
    def __iter__(self) -> 'ElementChildIterator[AnyStr]': ...
    def __next__(self) -> 'Element[AnyStr]': ...

class Attrib(Generic[AnyStr]):
    def __setitem__(self, key: Union[AnyStr, QName], value: AnyStr) -> None :...
    def __delitem__(self, key: Union[AnyStr, QName]) -> None: ...
    def update(self,
               sequence_or_dict: Union[Sequence[Tuple[AnyStr, AnyStr]],
                                       Mapping[AnyStr, AnyStr]]) -> None: ...
    def pop(self, key: AnyStr, default: AnyStr) -> AnyStr: ...
    def clear(self) -> None: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> DictAnyStr: ...
    def __deepcopy__(self, memo: Dict[Any, Any]) -> DictAnyStr: ...
    def __getitem__(self, key: Union[AnyStr, QName]) -> AnyStr: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, key: AnyStr, default: AnyStr = ...) -> Optional[AnyStr]: ...
    def keys(self) -> ListAnyStr: ...
    def __iter__(self) -> Iterator[AnyStr]: ...  # actually _AttribIterator
    def iterkeys(self) -> Iterator[AnyStr]: ...
    def values(self) -> ListAnyStr: ...
    def itervalues(self) -> Iterator[AnyStr]: ...
    def items(self) -> List[Tuple[AnyStr, AnyStr]]: ...
    def iteritems(self) -> Iterator[Tuple[AnyStr, AnyStr]]: ...
    def has_key(self, key: Union[AnyStr, QName]) -> bool: ...
    def __contains__(self, key: AnyStr) -> bool: ...
    def __richcmp__(self, other: 'Attrib[AnyStr]', op: int) -> bool: ...


class ElementTree(Generic[AnyStr]):
    @property
    def parse(self) -> XMLParser: ...
    def getpath(self, element: Element[AnyStr]) -> str: ...
    def getroot(self) -> Element[AnyStr]: ...
    def write(self,
              file: Union[AnyStr, IO[Any]],
              encoding: AnyStr = ...,
              method: AnyStr = ...,
              pretty_print: bool = ...,
              xml_declaration: Any = ...,
              with_tail: Any = ...,
              standalone: bool = ...,
              compression: int = ...,
              exclusive: bool = ...,
              with_comments: bool = ...,
              inclusive_ns_prefixes: ListAnyStr = ...) -> None: ...
    def write_c14n(self,
                   file: Union[AnyStr, IO[Any]],
                   with_comments: bool = ...,
                   compression: int = ...,
                   inclusive_ns_prefixes: Iterable[AnyStr] = ...) -> None: ...
    def _setroot(self, root: Element[AnyStr]) -> None: ...
    def xpath(self,
              _path: AnyStr,
              namespaces: Optional[DictAnyStr] = ...,
              extensions: Any = ...,
              smart_strings: bool = ...,
              **_variables: XPathObject) -> XPathObject: ...
    def xslt(self,
             _xslt: XSLT,
             extensions: Optional[Dict_Tuple2AnyStr_Any] = ...,
             access_control: Optional[XSLTAccessControl] = ...,
             **_variables: Any) -> 'ElementTree[AnyStr]': ...


